name: Laboratorio
on: workflow_dispatch 
jobs:
  first_job:
    runs-on: ubuntu-18.04
    steps:
    - name: Ola Mundo
      run: echo "Hello World"
    - name: Adeus Mundo
      run: echo "Farewell World"
